package com.fakhama.sales

object I18n {
    private val fa = mapOf(
        "app" to "فروش عمده فخامة", "home" to "خانه", "newOrder" to "سفارش جدید", "customers" to "مشتریان", "catalog" to "کاتالوگ پارچه", "inventory" to "انبار", "orders" to "سفارشات", "accounts" to "حساب مشتریان", "settings" to "تنظیمات", "todaySales" to "فروش امروز", "todayOrders" to "سفارش امروز", "receivables" to "مطالبات", "lowStock" to "کم‌موجود", "search" to "جستجو", "addCustomer" to "مشتری جدید", "addFabric" to "پارچه جدید", "name" to "نام", "phone" to "موبایل", "area" to "منطقه", "marketer" to "بازاریاب", "save" to "ذخیره", "cancel" to "انصراف", "selectCustomer" to "انتخاب مشتری", "selectFabric" to "انتخاب پارچه", "cart" to "سبد سفارش", "quantity" to "مقدار", "price" to "قیمت", "stock" to "موجودی", "total" to "جمع", "discount" to "تخفیف", "paid" to "پرداخت", "balance" to "مانده", "note" to "یادداشت", "confirmOrder" to "ثبت سفارش", "whatsapp" to "ارسال واتساپ", "newPayment" to "ثبت پرداخت", "language" to "زبان", "orderSaved" to "سفارش ثبت شد", "empty" to "موردی وجود ندارد", "back" to "بازگشت", "catalogName" to "کاتالوگ", "code" to "کد", "color" to "رنگ", "unit" to "واحد", "openingBalance" to "مانده اولیه", "customerAccount" to "حساب مشتری", "orderNo" to "شماره سفارش"
    )
    private val ar = mapOf(
        "app" to "مبيعات الفخامة", "home" to "الرئيسية", "newOrder" to "طلب جديد", "customers" to "العملاء", "catalog" to "كتالوج الأقمشة", "inventory" to "المخزون", "orders" to "الطلبات", "accounts" to "حسابات العملاء", "settings" to "الإعدادات", "todaySales" to "مبيعات اليوم", "todayOrders" to "طلبات اليوم", "receivables" to "المستحقات", "lowStock" to "مخزون منخفض", "search" to "بحث", "addCustomer" to "عميل جديد", "addFabric" to "قماش جديد", "name" to "الاسم", "phone" to "الهاتف", "area" to "المنطقة", "marketer" to "المندوب", "save" to "حفظ", "cancel" to "إلغاء", "selectCustomer" to "اختر العميل", "selectFabric" to "اختر القماش", "cart" to "سلة الطلب", "quantity" to "الكمية", "price" to "السعر", "stock" to "المخزون", "total" to "الإجمالي", "discount" to "الخصم", "paid" to "المدفوع", "balance" to "الباقي", "note" to "ملاحظة", "confirmOrder" to "تسجيل الطلب", "whatsapp" to "إرسال واتساب", "newPayment" to "تسجيل دفعة", "language" to "اللغة", "orderSaved" to "تم تسجيل الطلب", "empty" to "لا توجد بيانات", "back" to "رجوع", "catalogName" to "الكتالوج", "code" to "الكود", "color" to "اللون", "unit" to "الوحدة", "openingBalance" to "الرصيد الافتتاحي", "customerAccount" to "حساب العميل", "orderNo" to "رقم الطلب"
    )
    private val en = mapOf(
        "app" to "Fakhama Wholesale", "home" to "Home", "newOrder" to "New Order", "customers" to "Customers", "catalog" to "Fabric Catalog", "inventory" to "Inventory", "orders" to "Orders", "accounts" to "Customer Accounts", "settings" to "Settings", "todaySales" to "Today's Sales", "todayOrders" to "Today's Orders", "receivables" to "Receivables", "lowStock" to "Low Stock", "search" to "Search", "addCustomer" to "New Customer", "addFabric" to "New Fabric", "name" to "Name", "phone" to "Mobile", "area" to "Area", "marketer" to "Marketer", "save" to "Save", "cancel" to "Cancel", "selectCustomer" to "Select Customer", "selectFabric" to "Select Fabric", "cart" to "Order Cart", "quantity" to "Quantity", "price" to "Price", "stock" to "Stock", "total" to "Total", "discount" to "Discount", "paid" to "Paid", "balance" to "Balance", "note" to "Note", "confirmOrder" to "Save Order", "whatsapp" to "Send WhatsApp", "newPayment" to "Record Payment", "language" to "Language", "orderSaved" to "Order saved", "empty" to "No data", "back" to "Back", "catalogName" to "Catalog", "code" to "Code", "color" to "Color", "unit" to "Unit", "openingBalance" to "Opening Balance", "customerAccount" to "Customer Account", "orderNo" to "Order No."
    )
    fun t(language: AppLanguage, key: String): String = when (language) { AppLanguage.FA -> fa; AppLanguage.AR -> ar; AppLanguage.EN -> en }[key] ?: key
}
